### ISSUE TITLE
running `make.bat html` fails on Windows

### ISSUE THREAD

**Issue by SSE4** [conan-io/docs#1258]
I am running into this issue:
```
C:\bincrafters\docs>make.bat html
Running Sphinx v2.0.1

Exception occurred:
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\enchant\_enchant.py", line 102, in <module>
    raise WinError()
OSError: [WinError 193] <no description>
The full traceback has been saved in C:\Users\SSE4\AppData\Local\Temp\sphinx-err-og3fpjol.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
and **sphinx-err-og3fpjol.log** contains:
```
# Sphinx version: 2.0.1
# Python version: 3.6.5 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinx\cmd\build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinx\application.py", line 227, in __init__
    self.setup_extension(extension)
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinx\application.py", line 379, in setup_extension
    self.registry.load_extension(self, extname)
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinx\registry.py", line 473, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinxcontrib\spelling\__init__.py", line 5, in <module>
    from .builder import SpellingBuilder
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinxcontrib\spelling\builder.py", line 18, in <module>
    from enchant.tokenize import EmailFilter, WikiWordFilter
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\enchant\__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\enchant\_enchant.py", line 102, in <module>
    raise WinError()
OSError: [WinError 193] <no description>

```

**Comment by memsharded** [comment]
It works for me in Windows with these requirements
```
Package                  Version
------------------------ ---------
alabaster                0.7.11
Babel                    2.6.0
certifi                  2018.8.13
chardet                  3.0.4
colorama                 0.3.9
docutils                 0.14
idna                     2.7
imagesize                1.0.0
Jinja2                   2.10
MarkupSafe               1.0
packaging                17.1
pip                      18.0
pyenchant                2.0.0
Pygments                 2.2.0
pyparsing                2.2.0
pytz                     2018.5
requests                 2.19.1
setuptools               40.2.0
six                      1.11.0
snowballstemmer          1.2.1
Sphinx                   1.7.9
sphinxcontrib-spelling   4.2.1
sphinxcontrib-websupport 1.1.0
typing                   3.6.4
urllib3                  1.23
wheel                    0.31.1
```
The thing is that Sphinx is pinned to 1.7.9 in *requirements.txt*, and you are trying to run another Sphinx.

**Comment by SSE4** [comment]
run:
```
pip install sphinxcontrib.spelling==4.2.1
pip install sphinx==1.7.9
```
result is the same:
```
C:\bincrafters\docs>make.bat html
Running Sphinx v1.7.9

Exception occurred:
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\enchant\_enchant.py", line 102, in <module>
    raise WinError()
OSError: [WinError 193] <no description>
The full traceback has been saved in C:\Users\SSE4\AppData\Local\Temp\sphinx-err-rgvtwv6u.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```
# Sphinx version: 1.7.9
# Python version: 3.6.5 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinx\cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinx\application.py", line 191, in __init__
    self.setup_extension(extension)
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinx\application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinx\registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinxcontrib\spelling\__init__.py", line 5, in <module>
    from .builder import SpellingBuilder
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\sphinxcontrib\spelling\builder.py", line 18, in <module>
    from enchant.tokenize import EmailFilter, WikiWordFilter
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\enchant\__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\enchant\_enchant.py", line 102, in <module>
    raise WinError()
OSError: [WinError 193] <no description>

```

**Comment by danimtb** [comment]
Working from my side too with Python 3.7.0

These were the steps I did:

```
$ mkvirtualenv test_docs
$ pip install -r requirements.txt
$ make.bat html
```

Are you running in a virtual environment?

**Comment by SSE4** [comment]
@danimtb same problem
```
C:\Users\SSE4\AppData\Local\Programs\Python\Python36\Scripts>pip install virtualenvwrapper-win
Collecting virtualenvwrapper-win
  Downloading https://files.pythonhosted.org/packages/f5/23/4cba98733b9122219ce67177d745e4984b524b867cf3728eaa807ea21919/virtualenvwrapper-win-1.2.5.tar.gz
Requirement already satisfied: virtualenv in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from virtualenvwrapper-win) (16.5.0)
Installing collected packages: virtualenvwrapper-win
  Running setup.py install for virtualenvwrapper-win ... done
Successfully installed virtualenvwrapper-win-1.2.5

C:\Users\SSE4\AppData\Local\Programs\Python\Python36\Scripts>cd C:\bincrafters\docs

C:\bincrafters\docs>mkvirtualenv test_docs
 C:\Users\SSE4\Envs is not a directory, creating
Using base prefix 'c:\\users\\sse4\\appdata\\local\\programs\\python\\python36'
New python executable in C:\Users\SSE4\Envs\test_docs\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

C:\bincrafters\docs>pip install -r requirements.txt
Requirement already satisfied: sphinx==1.7.9 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 1)) (1.7.9)
Requirement already satisfied: sphinxcontrib-spelling in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 2)) (4.2.1)
Requirement already satisfied: six>=1.5 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (1.11.0)
Requirement already satisfied: babel!=2.0,>=1.3 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: setuptools in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (39.0.1)
Requirement already satisfied: requests>=2.0.0 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: Pygments>=2.0 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: snowballstemmer>=1.1 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (1.2.1)
Requirement already satisfied: packaging in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (17.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (0.7.12)
Requirement already satisfied: docutils>=0.11 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (0.14)
Requirement already satisfied: sphinxcontrib-websupport in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: Jinja2>=2.3 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (2.10)
Requirement already satisfied: colorama>=0.3.5; sys_platform == "win32" in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (0.3.9)
Requirement already satisfied: imagesize in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinx==1.7.9->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: PyEnchant>=1.6.5 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from sphinxcontrib-spelling->-r requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: pytz>=0a in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from babel!=2.0,>=1.3->sphinx==1.7.9->-r requirements.txt (line 1)) (2019.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0.0->sphinx==1.7.9->-r requirements.txt (line 1)) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0.0->sphinx==1.7.9->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0.0->sphinx==1.7.9->-r requirements.txt (line 1)) (2.6)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0.0->sphinx==1.7.9->-r requirements.txt (line 1)) (1.22)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from packaging->sphinx==1.7.9->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages (from Jinja2>=2.3->sphinx==1.7.9->-r requirements.txt (line 1)) (1.0)

C:\bincrafters\docs>make.bat html
Running Sphinx v1.7.9

Exception occurred:
  File "c:\users\sse4\appdata\local\programs\python\python36\lib\site-packages\enchant\_enchant.py", line 102, in <module>
    raise WinError()
OSError: [WinError 193] <no description>
The full traceback has been saved in C:\Users\SSE4\AppData\Local\Temp\sphinx-err-ie528imi.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
I gonna try with 3.7.0

**Comment by SSE4** [comment]
same issue with 3.7:
```
C:\bincrafters\docs>make.bat html
Running Sphinx v1.7.9

Exception occurred:
  File "c:\users\sse4\appdata\local\programs\python\python37\lib\site-packages\enchant\_enchant.py", line 102, in <module>
    raise WinError()
OSError: [WinError 193] <no description>
The full traceback has been saved in C:\Users\SSE4\AppData\Local\Temp\sphinx-err-uobqfizj.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by danimtb** [comment]
I remember having this issue in the past with the enchant package not being available in windows for some reason, however, I think the issue was solved when updated python.

Please make sure you start the installation in a clean environment and post the results of ``pip freeze`` ere

**Comment by SSE4** [comment]
I've just did clean installation of python 3.7 and enchant libraries.
```
C:\bincrafters\docs>pip freeze
alabaster==0.7.12
Babel==2.6.0
certifi==2019.3.9
chardet==3.0.4
colorama==0.4.1
docutils==0.14
idna==2.8
imagesize==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
packaging==19.0
pyenchant==2.0.0
Pygments==2.3.1
pyparsing==2.4.0
pytz==2019.1
requests==2.21.0
six==1.12.0
snowballstemmer==1.2.1
Sphinx==1.7.9
sphinxcontrib-spelling==4.2.1
sphinxcontrib-websupport==1.1.0
urllib3==1.24.2
virtualenv==16.5.0
virtualenvwrapper-win==1.2.5
```

**Comment by danimtb** [comment]
I have the same environment except for:

```
virtualenv==16.5.0
virtualenvwrapper-win==1.2.5
```

that are not listed (I installed them globally, so I am not sure if they should appear).
No idea where the error comes from...

**Comment by danimtb** [comment]
Oh, ok seems it is something unfortunate: https://stackoverflow.com/questions/25983908/pyenchant-raises-winerror-193-on-import-using-python-3-3-4

Indeed my python interpreter is 32 bit...
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
```

**Comment by SSE4** [comment]
ah, yep, I am running x64 Windows and x64 python:
```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
```

**Comment by uilianries** [comment]
I had some trouble with pyenchant on Linux ... I needed to build the project from sources because the author just abandoned the python wrapper project and the library named listed in the package is outdated.

**Comment by danimtb** [comment]
Yes, I think this was needed when the spell check was introduced by a contributor. It works fine in Travis but in other configurations it is a bit problematic

**Comment by SSE4** [comment]
is there an opt out for it?

**Comment by danimtb** [comment]
The spell check is only run with ``make spell-check`` or something like that. So it is not needed to build the documentation.

Can this be closed?

**Comment by SSE4** [comment]
no idea, does `make html` imply `make spell-check`?

**Comment by danimtb** [comment]
no, those are separate commands

**Comment by danimtb** [comment]
Closing this one but please comment or reopen if you face this issue again. Thanks!
